=== rok4/pytools/src/rok4_tools/joincache_utils/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "JOINCACHE pregeneration configuration",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "datasources",
        "pyramid",
        "process"
    ],
    "properties": {
        "logger": {
            "type": "object",
            "additionalProperties": false,
            "description": "Param√®tres du logger",
            "properties": {
                "layout": {
                    "type": "string",
                    "description": "Log format, according to logging python library",
                    "default": "%(asctime)s %(levelname)s: %(message)s"
                },
                "file": {
                    "type": "string",
                    "description": "Path to log file. Standard output is used if not provided"
                },
                "level": {
                    "type": "string",
                    "description": "Log level",
                    "enum": [
                        "DEBUG",
                        "INFO",
                        "WARNING",
                        "ERROR",
                        "CRITICAL",
                        "NOTSET"
                    ],
                    "default": "WARNING"
                }
            }
        },
        "datasources": {
            "type": "array",
            "description": "Source pyramids",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": ["source", "bottom", "top"],
                "properties": {
                    "bottom": {
                        "type": "string",
                        "description": "Bottom level's usage for source pyramids"
                    },
                    "top": {
                        "type": "string",
                        "description": "Top level's usage for source pyramids"
                    },
                    "source": {
                        "type": "object",
                        "additionalProperties": false,
                        "description": "Pyramids as data source",
                        "required": ["type", "descriptors"],
                        "properties": {
                            "type": {
                                "type": "string",
                                "description": "Source type",
                                "enum": ["PYRAMIDS"]
                            },
                            "descriptors": {
                                "type": "array",
                                "description": "Paths to pyramids' descriptors (all with the same characteritics : TMS, formats...)",
                                "items": {
                                    "type": "string"
                                },
                                "minItems": 1
                            }
                        }
                    }
                }
            }
        },
        "pyramid": {
            "type": "object",
            "additionalProperties": false,
            "description": "Output pyramid's storage informations",
            "required": ["name", "root"],
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Output pyramid's name"
                },
                "root": {
                    "type": "string",
                    "description": "Storage root : a directory for FILE storage, pool name for CEPH storage, bucket name for S3 storage"
                },
                "mask": {
                    "type": "boolean",
                    "description": "Mask export ? If true, masks are used for processing.",
                    "default": false
                }
            }
        },
        "process": {
            "type": "object",
            "additionalProperties": false,
            "description": "Processing parameters",
            "required": ["directory"],
            "properties": {
                "directory": {
                    "type": "string",
                    "description": "Directory to write copies to process, FILE directory or S3/CEPH prefix"
                },
                "parallelization": {
                    "type": "integer",
                    "description": "Parallelization level, number of todo lists and agents working at the same time",
                    "minimum": 1,
                    "default": 1
                },
                "mask": {
                    "type": "boolean",
                    "description": "Source masks used for processing ?",
                    "default": false
                },
                "only_links": {
                    "type": "boolean",
                    "description": "Only links are made ? If true, only top slab will be considered and linked",
                    "default": false
                }
            }
        }
    }
}

=== rok4/pytools/src/rok4_tools/joincache_utils/example.json
{
    "logger": {
        "level": "INFO"
    },
    "datasources": [
        {
            "top": "0",
            "bottom": "10",
            "source": {
                "type": "PYRAMIDS",
                "descriptors": [
                    "s3://pyramids/SCAN1000_FXX_1.json",
                    "s3://pyramids/SCAN1000_FXX_2.json",
                    "s3://pyramids/SCAN1000_FXX_3.json"
                ]
            }
        }
    ],
    "pyramid": {
        "name": "joincache",
        "root": "pyramids"
    },
    "process": {
        "directory": "s3://bucket_temp/joincache",
        "parallelization": 2,
        "mask": true
    }
}
